services:
  orders-db:
    image: postgres:17
    container_name: ecommerce-orders-db
    hostname: ecommerce-orders-db
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5452:5432"
    volumes:
      - ecommerce-orders-db:/var/lib/postgresql/data
    networks:
      - ecommerce

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: ecommerce-order-service
    environment:
      FLASK_ENV: production
      SQLALCHEMY_DATABASE_URI: postgresql://${AUTH_POSTGRES_USER}:${AUTH_POSTGRES_PASSWORD}@orders-db:5432/${AUTH_POSTGRES_DBNAME}
    depends_on:
      - orders-db
    ports:
      - "80:5000"
    networks:
      - ecommerce
    restart: unless-stopped

 
volumes:
  ecommerce-orders-db:
    driver: local
    name: ecommerce-orders-db

networks:
  ecommerce:
    driver: bridge
    name: ecommerce
