services:
  inventory-db:
    image: postgres:17
    container_name: ecommerce-inventory-db
    hostname: ecommerce-inventory-db
    environment:
      POSTGRES_USER: ${INV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${INV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${INV_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5451:5432"
    volumes:
      - ecommerce-inventory-db:/var/lib/postgresql/data
    networks:
      - ecommerce

  inventory-service:
      build:
        context: .
        dockerfile: Dockerfile
        platforms:
          - linux/amd64
          - linux/arm64
      container_name: ecommerce-inventory-service
      environment:
        FLASK_ENV: production
        SQLALCHEMY_DATABASE_URI: postgresql://${AUTH_POSTGRES_USER}:${AUTH_POSTGRES_PASSWORD}@inventory-db:5432/${AUTH_POSTGRES_DBNAME}
      depends_on:
        - inventory-db
      ports:
        - "80:5000"
      networks:
        - ecommerce
      restart: unless-stopped

volumes:
  ecommerce-inventory-db:
    driver: local
    name: ecommerce-inventory-db

networks:
  ecommerce:
    driver: bridge
    name: ecommerce
