services:
  auth-db:
    image: postgres:17
    container_name: ecommerce-auth-db
    hostname: ecommerce-auth-db
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5450:5432"
    volumes:
      - ecommerce-auth-db:/var/lib/postgresql/data
    networks:
      - ecommerce

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: ecommerce-auth-service
    environment:
      FLASK_ENV: production
      SQLALCHEMY_DATABASE_URI: postgresql://${AUTH_POSTGRES_USER}:${AUTH_POSTGRES_PASSWORD}@auth-db:5432/${AUTH_POSTGRES_DBNAME}
    depends_on:
      - auth-db
    ports:
      - "80:5000"
    networks:
      - ecommerce
    restart: unless-stopped



volumes:
  ecommerce-auth-db:
    driver: local
    name: ecommerce-auth-db

networks:
  ecommerce:
    driver: bridge
    name: ecommerce
