services:
  auth-db:
    image: postgres:17
    container_name: ecommerce-auth-db
    hostname: ecommerce-auth-db
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5450:5432"
    volumes:
      - ecommerce-auth-db:/var/lib/postgresql/data
    networks:
      - ecommerce



volumes:
  ecommerce-auth-db:
    driver: local
    name: ecommerce-auth-db

networks:
  ecommerce:
    driver: bridge
    name: ecommerce
